services:
  - docker

dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

# Test website to run attack
before_install:
  - docker run -d --rm -p 80:3000 bkimminich/juice-shop

# command to install dependencies and tests tooling
install:
  - pip install -e .[tests]

# command to run tests
script:
  - make full_test
  - make criticalint

#command to generate documentation
#after_success:
#  - make doc
#  - make metrics
